# Generated by Django 4.1.1 on 2022-09-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planting', '0005_alter_plantingdateplannerc_first_weeding_after_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=256, null=True)),
                ('lastfirstname', models.CharField(blank=True, max_length=256, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('yob', models.IntegerField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.county')),
                ('subcounty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.subcounty')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.ward')),
            ],
        ),
    ]
