# Generated by Django 4.1.1 on 2022-09-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0004_remove_valuechainvariety_valuechain_county_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingdateplannerc',
            name='first_weeding_after_days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantingdateplannerc',
            name='second_weeding_after_days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
