# Generated by Django 4.1.1 on 2022-09-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0005_alter_plantingdateplannerc_first_weeding_after_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingdateplannerc',
            name='release_name',
        ),
        migrations.CreateModel(
            name='ValueChainVariety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('release_name', models.CharField(max_length=256)),
                ('valuechain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.valuechain')),
            ],
        ),
        migrations.AlterField(
            model_name='plantingdateplannerc',
            name='vc_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.valuechainvariety'),
        ),
    ]
