# Generated by Django 4.1.1 on 2022-09-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planting', '0005_alter_plantingdateplannerc_first_weeding_after_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOwnership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MyFarm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(blank=True, max_length=256, null=True)),
                ('vc_variety', models.CharField(blank=True, max_length=256, null=True)),
                ('lat', models.FloatField(blank=True, max_length=20, null=True)),
                ('lon', models.FloatField(blank=True, max_length=20, null=True)),
                ('farm_size_ha', models.FloatField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.county')),
                ('farm_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.farmownership')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.farmerprofile')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.subcounty')),
                ('valuechain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.valuechain')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.ward')),
            ],
        ),
    ]
