# Generated by Django 4.1.1 on 2022-09-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0006_remove_plantingdateplannerc_release_name_and_more'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfarm',
            name='vc_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.valuechainvariety'),
        ),
    ]
