# Generated by Django 4.1.1 on 2022-09-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfarm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.profile'),
        ),
    ]
