# Generated by Django 4.1.1 on 2022-09-21 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0005_alter_myfarm_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfarm',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='myfarm',
            name='status',
            field=models.IntegerField(choices=[(0, 'Idle Land'), (1, 'Active Land')], default=0),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_farms', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
