# Generated by Django 4.1.1 on 2022-09-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_myfarm_options_myfarm_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfarm',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
