# Generated by Django 4.1.1 on 2022-09-28 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planting', '0006_remove_plantingdateplannerc_release_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0007_myfarm_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myfarm',
            options={'ordering': ['-owner']},
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.county'),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='farm_ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farmownership'),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_farms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Idle Land'), (1, 'Active Land')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.subcounty'),
        ),
        migrations.AlterField(
            model_name='myfarm',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planting.ward'),
        ),
    ]
